services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - mongo_network

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo_network

volumes:
  mongo_data:
    driver: local

networks:
  mongo_network:
    driver: bridge
